### ISSUE TITLE
Please check some parameters when calculating 'totallocked'

### ISSUE THREAD

**Issue by winter520** [antonnell/multibridge.xyz#1]
Please check some parameters when calculating 'totallocked'

**Comment by winter520** [comment]
https://github.com/antonnell/multibridge.xyz/blob/985d08c0da392ca8d9e3c3a4d654f5d28b875626/stores/swapStore.jsx#L877

**Comment by antonnell** [comment]
I believe this has been fixed in one of the previous commits. Closing for now.
