### ISSUE TITLE
About how to contribute code

### ISSUE THREAD

**Issue by GoDotDotDot** [antonnell/multibridge.xyz#4]
I'm a front-end development engineer, I am interested in DEFI, and I am also a fan of AC. I would like to know if the team needs volunteers now. I really hope to contribute some codes.

Looking forward to respond, thx.

**Comment by yopoing** [comment]
> I'm a front-end development engineer, I am interested in DEFI, and I am also a fan of AC. I would like to know if the team needs volunteers now. I really hope to contribute some codes.
> 
> Looking forward to respond, thx.

I want you!

**Comment by antonnell** [comment]
Anyone that is interested in getting involved is welcome to get involved. 
Submit a PR, if it is worth merging in, I'll merge it in.

There's no official "Task List".

**Comment by GoDotDotDot** [comment]
Ok, got.

**Comment by antonnell** [comment]
Closing this issue.
